#ifndef MUSL_BSD_LAYOUT_BASELINE_X86_64_H
#define MUSL_BSD_LAYOUT_BASELINE_X86_64_H

#define LAYOUT_FTS_SIZE 72
#define LAYOUT_FTS_OFF_CUR 0
#define LAYOUT_FTS_OFF_CHILD 8
#define LAYOUT_FTS_OFF_ARRAY 16
#define LAYOUT_FTS_OFF_DEV 24
#define LAYOUT_FTS_OFF_PATH 32
#define LAYOUT_FTS_OFF_RFD 40
#define LAYOUT_FTS_OFF_PATHLEN 44
#define LAYOUT_FTS_OFF_NITEMS 48
#define LAYOUT_FTS_OFF_COMPAR 56
#define LAYOUT_FTS_OFF_OPTIONS 64

#define LAYOUT_FTSENT_SIZE 128
#define LAYOUT_FTSENT_OFF_CYCLE 0
#define LAYOUT_FTSENT_OFF_PARENT 8
#define LAYOUT_FTSENT_OFF_LINK 16
#define LAYOUT_FTSENT_OFF_NUMBER 24
#define LAYOUT_FTSENT_OFF_POINTER 32
#define LAYOUT_FTSENT_OFF_ACCPATH 40
#define LAYOUT_FTSENT_OFF_PATH 48
#define LAYOUT_FTSENT_OFF_ERRNO 56
#define LAYOUT_FTSENT_OFF_SYMFD 60
#define LAYOUT_FTSENT_OFF_PATHLEN 64
#define LAYOUT_FTSENT_OFF_NAMELEN 68
#define LAYOUT_FTSENT_OFF_INO 72
#define LAYOUT_FTSENT_OFF_DEV 80
#define LAYOUT_FTSENT_OFF_NLINK 88
#define LAYOUT_FTSENT_OFF_LEVEL 96
#define LAYOUT_FTSENT_OFF_INFO 100
#define LAYOUT_FTSENT_OFF_FLAGS 102
#define LAYOUT_FTSENT_OFF_INSTR 104
#define LAYOUT_FTSENT_OFF_STATP 112
#define LAYOUT_FTSENT_OFF_NAME 120

#define LAYOUT_OBSTACK_CHUNK_SIZE 24
#define LAYOUT_OBSTACK_CHUNK_OFF_LIMIT 0
#define LAYOUT_OBSTACK_CHUNK_OFF_PREV 8
#define LAYOUT_OBSTACK_CHUNK_OFF_CONTENTS 16

#define LAYOUT_OBSTACK_SIZE 88
#define LAYOUT_OBSTACK_OFF_CHUNK_SIZE 0
#define LAYOUT_OBSTACK_OFF_CHUNK 8
#define LAYOUT_OBSTACK_OFF_OBJECT_BASE 16
#define LAYOUT_OBSTACK_OFF_NEXT_FREE 24
#define LAYOUT_OBSTACK_OFF_CHUNK_LIMIT 32
#define LAYOUT_OBSTACK_OFF_TEMP 40
#define LAYOUT_OBSTACK_OFF_ALIGNMENT_MASK 48
#define LAYOUT_OBSTACK_OFF_CHUNKFUN 56
#define LAYOUT_OBSTACK_OFF_FREEFUN 64
#define LAYOUT_OBSTACK_OFF_EXTRA_ARG 72

#define LAYOUT_ARGP_OPTION_SIZE 48
#define LAYOUT_ARGP_OPTION_OFF_NAME 0
#define LAYOUT_ARGP_OPTION_OFF_KEY 8
#define LAYOUT_ARGP_OPTION_OFF_ARG 16
#define LAYOUT_ARGP_OPTION_OFF_FLAGS 24
#define LAYOUT_ARGP_OPTION_OFF_DOC 32
#define LAYOUT_ARGP_OPTION_OFF_GROUP 40

#define LAYOUT_ARGP_CHILD_SIZE 32
#define LAYOUT_ARGP_CHILD_OFF_ARGP 0
#define LAYOUT_ARGP_CHILD_OFF_FLAGS 8
#define LAYOUT_ARGP_CHILD_OFF_HEADER 16
#define LAYOUT_ARGP_CHILD_OFF_GROUP 24

#define LAYOUT_ARGP_SIZE 56
#define LAYOUT_ARGP_OFF_OPTIONS 0
#define LAYOUT_ARGP_OFF_PARSER 8
#define LAYOUT_ARGP_OFF_ARGS_DOC 16
#define LAYOUT_ARGP_OFF_DOC 24
#define LAYOUT_ARGP_OFF_CHILDREN 32
#define LAYOUT_ARGP_OFF_HELP_FILTER 40
#define LAYOUT_ARGP_OFF_ARGP_DOMAIN 48

#define LAYOUT_ARGP_STATE_SIZE 96
#define LAYOUT_ARGP_STATE_OFF_ROOT_ARGP 0
#define LAYOUT_ARGP_STATE_OFF_ARGC 8
#define LAYOUT_ARGP_STATE_OFF_ARGV 16
#define LAYOUT_ARGP_STATE_OFF_NEXT 24
#define LAYOUT_ARGP_STATE_OFF_FLAGS 28
#define LAYOUT_ARGP_STATE_OFF_ARG_NUM 32
#define LAYOUT_ARGP_STATE_OFF_QUOTED 36
#define LAYOUT_ARGP_STATE_OFF_INPUT 40
#define LAYOUT_ARGP_STATE_OFF_CHILD_INPUTS 48
#define LAYOUT_ARGP_STATE_OFF_HOOK 56
#define LAYOUT_ARGP_STATE_OFF_NAME 64
#define LAYOUT_ARGP_STATE_OFF_ERR_STREAM 72
#define LAYOUT_ARGP_STATE_OFF_OUT_STREAM 80
#define LAYOUT_ARGP_STATE_OFF_PSTATE 88

#endif /* MUSL_BSD_LAYOUT_BASELINE_X86_64_H */
