#include <stddef.h>

#include "fts.h"
#include "obstack.h"
#include "argp.h"

#include "tests/abi/layout_baseline_x86_64.h"

#define ASSERT_SIZE(type, expect) _Static_assert(sizeof(type) == (expect), "size mismatch: " #type)
#define ASSERT_OFFSET(type, field, expect) \
    _Static_assert(offsetof(type, field) == (expect), "offset mismatch: " #type "." #field)

ASSERT_SIZE(FTS, LAYOUT_FTS_SIZE);
ASSERT_OFFSET(FTS, fts_cur, LAYOUT_FTS_OFF_CUR);
ASSERT_OFFSET(FTS, fts_child, LAYOUT_FTS_OFF_CHILD);
ASSERT_OFFSET(FTS, fts_array, LAYOUT_FTS_OFF_ARRAY);
ASSERT_OFFSET(FTS, fts_dev, LAYOUT_FTS_OFF_DEV);
ASSERT_OFFSET(FTS, fts_path, LAYOUT_FTS_OFF_PATH);
ASSERT_OFFSET(FTS, fts_rfd, LAYOUT_FTS_OFF_RFD);
ASSERT_OFFSET(FTS, fts_pathlen, LAYOUT_FTS_OFF_PATHLEN);
ASSERT_OFFSET(FTS, fts_nitems, LAYOUT_FTS_OFF_NITEMS);
ASSERT_OFFSET(FTS, fts_compar, LAYOUT_FTS_OFF_COMPAR);
ASSERT_OFFSET(FTS, fts_options, LAYOUT_FTS_OFF_OPTIONS);

ASSERT_SIZE(FTSENT, LAYOUT_FTSENT_SIZE);
ASSERT_OFFSET(FTSENT, fts_cycle, LAYOUT_FTSENT_OFF_CYCLE);
ASSERT_OFFSET(FTSENT, fts_parent, LAYOUT_FTSENT_OFF_PARENT);
ASSERT_OFFSET(FTSENT, fts_link, LAYOUT_FTSENT_OFF_LINK);
ASSERT_OFFSET(FTSENT, fts_number, LAYOUT_FTSENT_OFF_NUMBER);
ASSERT_OFFSET(FTSENT, fts_pointer, LAYOUT_FTSENT_OFF_POINTER);
ASSERT_OFFSET(FTSENT, fts_accpath, LAYOUT_FTSENT_OFF_ACCPATH);
ASSERT_OFFSET(FTSENT, fts_path, LAYOUT_FTSENT_OFF_PATH);
ASSERT_OFFSET(FTSENT, fts_errno, LAYOUT_FTSENT_OFF_ERRNO);
ASSERT_OFFSET(FTSENT, fts_symfd, LAYOUT_FTSENT_OFF_SYMFD);
ASSERT_OFFSET(FTSENT, fts_pathlen, LAYOUT_FTSENT_OFF_PATHLEN);
ASSERT_OFFSET(FTSENT, fts_namelen, LAYOUT_FTSENT_OFF_NAMELEN);
ASSERT_OFFSET(FTSENT, fts_ino, LAYOUT_FTSENT_OFF_INO);
ASSERT_OFFSET(FTSENT, fts_dev, LAYOUT_FTSENT_OFF_DEV);
ASSERT_OFFSET(FTSENT, fts_nlink, LAYOUT_FTSENT_OFF_NLINK);
ASSERT_OFFSET(FTSENT, fts_level, LAYOUT_FTSENT_OFF_LEVEL);
ASSERT_OFFSET(FTSENT, fts_info, LAYOUT_FTSENT_OFF_INFO);
ASSERT_OFFSET(FTSENT, fts_flags, LAYOUT_FTSENT_OFF_FLAGS);
ASSERT_OFFSET(FTSENT, fts_instr, LAYOUT_FTSENT_OFF_INSTR);
ASSERT_OFFSET(FTSENT, fts_statp, LAYOUT_FTSENT_OFF_STATP);
ASSERT_OFFSET(FTSENT, fts_name, LAYOUT_FTSENT_OFF_NAME);

ASSERT_SIZE(struct _obstack_chunk, LAYOUT_OBSTACK_CHUNK_SIZE);
ASSERT_OFFSET(struct _obstack_chunk, limit, LAYOUT_OBSTACK_CHUNK_OFF_LIMIT);
ASSERT_OFFSET(struct _obstack_chunk, prev, LAYOUT_OBSTACK_CHUNK_OFF_PREV);
ASSERT_OFFSET(struct _obstack_chunk, contents, LAYOUT_OBSTACK_CHUNK_OFF_CONTENTS);

ASSERT_SIZE(struct obstack, LAYOUT_OBSTACK_SIZE);
ASSERT_OFFSET(struct obstack, chunk_size, LAYOUT_OBSTACK_OFF_CHUNK_SIZE);
ASSERT_OFFSET(struct obstack, chunk, LAYOUT_OBSTACK_OFF_CHUNK);
ASSERT_OFFSET(struct obstack, object_base, LAYOUT_OBSTACK_OFF_OBJECT_BASE);
ASSERT_OFFSET(struct obstack, next_free, LAYOUT_OBSTACK_OFF_NEXT_FREE);
ASSERT_OFFSET(struct obstack, chunk_limit, LAYOUT_OBSTACK_OFF_CHUNK_LIMIT);
ASSERT_OFFSET(struct obstack, temp, LAYOUT_OBSTACK_OFF_TEMP);
ASSERT_OFFSET(struct obstack, alignment_mask, LAYOUT_OBSTACK_OFF_ALIGNMENT_MASK);
ASSERT_OFFSET(struct obstack, chunkfun, LAYOUT_OBSTACK_OFF_CHUNKFUN);
ASSERT_OFFSET(struct obstack, freefun, LAYOUT_OBSTACK_OFF_FREEFUN);
ASSERT_OFFSET(struct obstack, extra_arg, LAYOUT_OBSTACK_OFF_EXTRA_ARG);

ASSERT_SIZE(struct argp_option, LAYOUT_ARGP_OPTION_SIZE);
ASSERT_OFFSET(struct argp_option, name, LAYOUT_ARGP_OPTION_OFF_NAME);
ASSERT_OFFSET(struct argp_option, key, LAYOUT_ARGP_OPTION_OFF_KEY);
ASSERT_OFFSET(struct argp_option, arg, LAYOUT_ARGP_OPTION_OFF_ARG);
ASSERT_OFFSET(struct argp_option, flags, LAYOUT_ARGP_OPTION_OFF_FLAGS);
ASSERT_OFFSET(struct argp_option, doc, LAYOUT_ARGP_OPTION_OFF_DOC);
ASSERT_OFFSET(struct argp_option, group, LAYOUT_ARGP_OPTION_OFF_GROUP);

ASSERT_SIZE(struct argp_child, LAYOUT_ARGP_CHILD_SIZE);
ASSERT_OFFSET(struct argp_child, argp, LAYOUT_ARGP_CHILD_OFF_ARGP);
ASSERT_OFFSET(struct argp_child, flags, LAYOUT_ARGP_CHILD_OFF_FLAGS);
ASSERT_OFFSET(struct argp_child, header, LAYOUT_ARGP_CHILD_OFF_HEADER);
ASSERT_OFFSET(struct argp_child, group, LAYOUT_ARGP_CHILD_OFF_GROUP);

ASSERT_SIZE(struct argp, LAYOUT_ARGP_SIZE);
ASSERT_OFFSET(struct argp, options, LAYOUT_ARGP_OFF_OPTIONS);
ASSERT_OFFSET(struct argp, parser, LAYOUT_ARGP_OFF_PARSER);
ASSERT_OFFSET(struct argp, args_doc, LAYOUT_ARGP_OFF_ARGS_DOC);
ASSERT_OFFSET(struct argp, doc, LAYOUT_ARGP_OFF_DOC);
ASSERT_OFFSET(struct argp, children, LAYOUT_ARGP_OFF_CHILDREN);
ASSERT_OFFSET(struct argp, help_filter, LAYOUT_ARGP_OFF_HELP_FILTER);
ASSERT_OFFSET(struct argp, argp_domain, LAYOUT_ARGP_OFF_ARGP_DOMAIN);

ASSERT_SIZE(struct argp_state, LAYOUT_ARGP_STATE_SIZE);
ASSERT_OFFSET(struct argp_state, root_argp, LAYOUT_ARGP_STATE_OFF_ROOT_ARGP);
ASSERT_OFFSET(struct argp_state, argc, LAYOUT_ARGP_STATE_OFF_ARGC);
ASSERT_OFFSET(struct argp_state, argv, LAYOUT_ARGP_STATE_OFF_ARGV);
ASSERT_OFFSET(struct argp_state, next, LAYOUT_ARGP_STATE_OFF_NEXT);
ASSERT_OFFSET(struct argp_state, flags, LAYOUT_ARGP_STATE_OFF_FLAGS);
ASSERT_OFFSET(struct argp_state, arg_num, LAYOUT_ARGP_STATE_OFF_ARG_NUM);
ASSERT_OFFSET(struct argp_state, quoted, LAYOUT_ARGP_STATE_OFF_QUOTED);
ASSERT_OFFSET(struct argp_state, input, LAYOUT_ARGP_STATE_OFF_INPUT);
ASSERT_OFFSET(struct argp_state, child_inputs, LAYOUT_ARGP_STATE_OFF_CHILD_INPUTS);
ASSERT_OFFSET(struct argp_state, hook, LAYOUT_ARGP_STATE_OFF_HOOK);
ASSERT_OFFSET(struct argp_state, name, LAYOUT_ARGP_STATE_OFF_NAME);
ASSERT_OFFSET(struct argp_state, err_stream, LAYOUT_ARGP_STATE_OFF_ERR_STREAM);
ASSERT_OFFSET(struct argp_state, out_stream, LAYOUT_ARGP_STATE_OFF_OUT_STREAM);
ASSERT_OFFSET(struct argp_state, pstate, LAYOUT_ARGP_STATE_OFF_PSTATE);

int main(void) {
    return 0;
}
